services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "ep.host=${EP_HOST}"
      - "ep.type=primary"
      - "traefik.http.routers.frontend.rule=Host(`${EP_HOST}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./db.json:/app/db.json:ro
      - ./public:/app/public:ro
      - ./routes.json:/app/routes.json:ro
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - CORS_ORIGIN=*
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/categories"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "ep.host=${EP_HOST}"
      - "ep.type=secondary"
      - "traefik.http.routers.backend.rule=Host(`${EP_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.backend-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-strip@docker"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

networks:
  app-network:
    driver: bridge 