services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "ep.host=${EP_HOST}"
      - "ep.type=primary"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./db.json:/app/db.json:ro
      - ./public:/app/public:ro
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/categories"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "ep.host=${EP_HOST}"
      - "ep.type=secondary"
      - "ep.path=/api"

networks:
  app-network:
    driver: bridge 