version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=https://api.${DOMAIN}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.${PROJECT_NAME}-frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./db.json:/app/db.json:ro
      - ./public:/app/public:ro
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/categories"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-backend.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.services.${PROJECT_NAME}-backend.loadbalancer.server.port=3000"

networks:
  app-network:
    driver: bridge 